num_show_pigs = 500
num_pigs_per_fence = 200
min_mean_to_median = 1
max_mean_to_median = 500
pmb_rtp = 1.0
simulation_trials = 1000
test_spins = [ 10, 20, 50,]
test_spins_weights = [ 0.6, 0.2, 0.2,]
score_type = "rtp"
max_trial_dist = 15
game_name = "blood_frenzy"
path_to_games = "../games/"
run_1000_batch = false
bet_type = "bonus"
threads_for_fence_construction = 5
threads_for_show_construction = 5
